//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizacionDatosCampaña.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicesxsd.cns.ws.corp.yanbal.com", ConfigurationName="WS.WSConsultora_SXSDImpl")]
    public interface WSConsultora_SXSDImpl {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (consultarCNSXCodigoRequest) del mensaje consultarCNSXCodigoRequest no coincide con el valor predeterminado (consultarCNSXCodigo)
        [System.ServiceModel.OperationContractAttribute(Action="consultarCNS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ActualizacionDatosCampaña.WS.consultarCNSXCodigoResponse consultarCNSXCodigo(ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarCNS", ReplyAction="*")]
        System.Threading.Tasks.Task<ActualizacionDatosCampaña.WS.consultarCNSXCodigoResponse> consultarCNSXCodigoAsync(ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (crearContactoRequest) del mensaje crearContactoRequest no coincide con el valor predeterminado (crearContacto)
        [System.ServiceModel.OperationContractAttribute(Action="crearContacto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ActualizacionDatosCampaña.WS.crearContactoResponse crearContacto(ActualizacionDatosCampaña.WS.crearContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="crearContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<ActualizacionDatosCampaña.WS.crearContactoResponse> crearContactoAsync(ActualizacionDatosCampaña.WS.crearContactoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class IntegracionWSReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cabecera cabeceraField;
        
        private Detalle detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Cabecera cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Detalle detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.comunsxsd.ws.corp.yanbal.com")]
    public partial class Cabecera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoInterfazField;
        
        private string usuarioAplicacionField;
        
        private string codigoAplicacionField;
        
        private string codigoPaisField;
        
        private CodigoPaisODType[] codigosPaisODField;
        
        private string idTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codigoInterfaz {
            get {
                return this.codigoInterfazField;
            }
            set {
                this.codigoInterfazField = value;
                this.RaisePropertyChanged("codigoInterfaz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
                this.RaisePropertyChanged("codigoAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string codigoPais {
            get {
                return this.codigoPaisField;
            }
            set {
                this.codigoPaisField = value;
                this.RaisePropertyChanged("codigoPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("codigoPaisOD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CodigoPaisODType[] codigosPaisOD {
            get {
                return this.codigosPaisODField;
            }
            set {
                this.codigosPaisODField = value;
                this.RaisePropertyChanged("codigosPaisOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.comunsxsd.ws.corp.yanbal.com")]
    public partial class CodigoPaisODType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DetalleSalida", Namespace="http://to.rcreconsf.ws.corp.yanbal.com")]
    public partial class DetalleSalida1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.comunsxsd.ws.corp.yanbal.com")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="IntegracionWSResp", Namespace="http://to.rcreconsf.ws.corp.yanbal.com")]
    public partial class IntegracionWSResp1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cabecera cabeceraField;
        
        private DetalleSalida1 detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Cabecera cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public DetalleSalida1 detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.rcreconsf.ws.corp.yanbal.com")]
    public partial class configuracionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> cntRegistrosField;
        
        private bool cntRegistrosFieldSpecified;
        
        private System.Nullable<int> numBloqueField;
        
        private bool numBloqueFieldSpecified;
        
        private System.Nullable<int> numTotBloquesField;
        
        private bool numTotBloquesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> cntRegistros {
            get {
                return this.cntRegistrosField;
            }
            set {
                this.cntRegistrosField = value;
                this.RaisePropertyChanged("cntRegistros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cntRegistrosSpecified {
            get {
                return this.cntRegistrosFieldSpecified;
            }
            set {
                this.cntRegistrosFieldSpecified = value;
                this.RaisePropertyChanged("cntRegistrosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> numBloque {
            get {
                return this.numBloqueField;
            }
            set {
                this.numBloqueField = value;
                this.RaisePropertyChanged("numBloque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numBloqueSpecified {
            get {
                return this.numBloqueFieldSpecified;
            }
            set {
                this.numBloqueFieldSpecified = value;
                this.RaisePropertyChanged("numBloqueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> numTotBloques {
            get {
                return this.numTotBloquesField;
            }
            set {
                this.numTotBloquesField = value;
                this.RaisePropertyChanged("numTotBloques");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numTotBloquesSpecified {
            get {
                return this.numTotBloquesFieldSpecified;
            }
            set {
                this.numTotBloquesFieldSpecified = value;
                this.RaisePropertyChanged("numTotBloquesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.rcreconsf.ws.corp.yanbal.com")]
    public partial class crearContactoReqType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private configuracionType configuracionField;
        
        private string datosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public configuracionType configuracion {
            get {
                return this.configuracionField;
            }
            set {
                this.configuracionField = value;
                this.RaisePropertyChanged("configuracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Detalle", Namespace="http://to.rcreconsf.ws.corp.yanbal.com")]
    public partial class Detalle1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private crearContactoReqType crearContactoReqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public crearContactoReqType crearContactoReq {
            get {
                return this.crearContactoReqField;
            }
            set {
                this.crearContactoReqField = value;
                this.RaisePropertyChanged("crearContactoReq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="IntegracionWSReq", Namespace="http://to.rcreconsf.ws.corp.yanbal.com")]
    public partial class IntegracionWSReq1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cabecera cabeceraField;
        
        private Detalle1 detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Cabecera cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Detalle1 detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class DireccionCompletaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private string estadoProvinciaField;
        
        private string ciudadField;
        
        private string barrioDistritoField;
        
        private string codZonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string estadoProvincia {
            get {
                return this.estadoProvinciaField;
            }
            set {
                this.estadoProvinciaField = value;
                this.RaisePropertyChanged("estadoProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string barrioDistrito {
            get {
                return this.barrioDistritoField;
            }
            set {
                this.barrioDistritoField = value;
                this.RaisePropertyChanged("barrioDistrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string codZona {
            get {
                return this.codZonaField;
            }
            set {
                this.codZonaField = value;
                this.RaisePropertyChanged("codZona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class ConsultoraJSXRtaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codConsultoraField;
        
        private string nombreCompletoField;
        
        private string nombresField;
        
        private string apePaternoField;
        
        private string apeMaternoField;
        
        private string sexoField;
        
        private string culturaField;
        
        private string codTituloField;
        
        private string tituloField;
        
        private System.Nullable<int> rankingField;
        
        private string codDirectoraField;
        
        private string nombreDirectoraField;
        
        private string codEjecutivaServiciosField;
        
        private string servicioEjecutivoField;
        
        private string coordinadorVentasField;
        
        private string emailField;
        
        private DireccionCompletaType direccionPersonalField;
        
        private DireccionCompletaType direccionEnvioField;
        
        private string idTipoDocumentoIdentidadField;
        
        private string tipoDocumentoIdentidadField;
        
        private string nroDocumentoIdentidadField;
        
        private string telefonoCasaField;
        
        private string telefonoMovilField;
        
        private string telefonoTrabajoField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codConsultora {
            get {
                return this.codConsultoraField;
            }
            set {
                this.codConsultoraField = value;
                this.RaisePropertyChanged("codConsultora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string apePaterno {
            get {
                return this.apePaternoField;
            }
            set {
                this.apePaternoField = value;
                this.RaisePropertyChanged("apePaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string apeMaterno {
            get {
                return this.apeMaternoField;
            }
            set {
                this.apeMaternoField = value;
                this.RaisePropertyChanged("apeMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string cultura {
            get {
                return this.culturaField;
            }
            set {
                this.culturaField = value;
                this.RaisePropertyChanged("cultura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string codTitulo {
            get {
                return this.codTituloField;
            }
            set {
                this.codTituloField = value;
                this.RaisePropertyChanged("codTitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int> ranking {
            get {
                return this.rankingField;
            }
            set {
                this.rankingField = value;
                this.RaisePropertyChanged("ranking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string codDirectora {
            get {
                return this.codDirectoraField;
            }
            set {
                this.codDirectoraField = value;
                this.RaisePropertyChanged("codDirectora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string nombreDirectora {
            get {
                return this.nombreDirectoraField;
            }
            set {
                this.nombreDirectoraField = value;
                this.RaisePropertyChanged("nombreDirectora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string codEjecutivaServicios {
            get {
                return this.codEjecutivaServiciosField;
            }
            set {
                this.codEjecutivaServiciosField = value;
                this.RaisePropertyChanged("codEjecutivaServicios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string servicioEjecutivo {
            get {
                return this.servicioEjecutivoField;
            }
            set {
                this.servicioEjecutivoField = value;
                this.RaisePropertyChanged("servicioEjecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string coordinadorVentas {
            get {
                return this.coordinadorVentasField;
            }
            set {
                this.coordinadorVentasField = value;
                this.RaisePropertyChanged("coordinadorVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public DireccionCompletaType direccionPersonal {
            get {
                return this.direccionPersonalField;
            }
            set {
                this.direccionPersonalField = value;
                this.RaisePropertyChanged("direccionPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public DireccionCompletaType direccionEnvio {
            get {
                return this.direccionEnvioField;
            }
            set {
                this.direccionEnvioField = value;
                this.RaisePropertyChanged("direccionEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", IsNullable=true, Order=18)]
        public string idTipoDocumentoIdentidad {
            get {
                return this.idTipoDocumentoIdentidadField;
            }
            set {
                this.idTipoDocumentoIdentidadField = value;
                this.RaisePropertyChanged("idTipoDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string tipoDocumentoIdentidad {
            get {
                return this.tipoDocumentoIdentidadField;
            }
            set {
                this.tipoDocumentoIdentidadField = value;
                this.RaisePropertyChanged("tipoDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string nroDocumentoIdentidad {
            get {
                return this.nroDocumentoIdentidadField;
            }
            set {
                this.nroDocumentoIdentidadField = value;
                this.RaisePropertyChanged("nroDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string telefonoCasa {
            get {
                return this.telefonoCasaField;
            }
            set {
                this.telefonoCasaField = value;
                this.RaisePropertyChanged("telefonoCasa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string telefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
                this.RaisePropertyChanged("telefonoMovil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string telefonoTrabajo {
            get {
                return this.telefonoTrabajoField;
            }
            set {
                this.telefonoTrabajoField = value;
                this.RaisePropertyChanged("telefonoTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class ConsultarConsultoraJSXRtaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsultoraJSXRtaType[] consultorasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("consultora", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultoraJSXRtaType[] consultoras {
            get {
                return this.consultorasField;
            }
            set {
                this.consultorasField = value;
                this.RaisePropertyChanged("consultoras");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class DetalleSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Respuesta respuestaField;
        
        private ConsultarConsultoraJSXRtaType datosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public ConsultarConsultoraJSXRtaType datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class IntegracionWSResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Cabecera cabeceraField;
        
        private DetalleSalida detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Cabecera cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
                this.RaisePropertyChanged("cabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public DetalleSalida detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class ConsultarConsultoraJSXEnvType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoBusquedaField;
        
        private string codBusquedaField;
        
        private string apePaternoField;
        
        private string apeMaternoField;
        
        private string nombresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string tipoBusqueda {
            get {
                return this.tipoBusquedaField;
            }
            set {
                this.tipoBusquedaField = value;
                this.RaisePropertyChanged("tipoBusqueda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codBusqueda {
            get {
                return this.codBusquedaField;
            }
            set {
                this.codBusquedaField = value;
                this.RaisePropertyChanged("codBusqueda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string apePaterno {
            get {
                return this.apePaternoField;
            }
            set {
                this.apePaternoField = value;
                this.RaisePropertyChanged("apePaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string apeMaterno {
            get {
                return this.apeMaternoField;
            }
            set {
                this.apeMaternoField = value;
                this.RaisePropertyChanged("apeMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://to.ccnsjsxsxsd.ws.corp.yanbal.com")]
    public partial class Detalle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsultarConsultoraJSXEnvType consultoraReqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public ConsultarConsultoraJSXEnvType consultoraReq {
            get {
                return this.consultoraReqField;
            }
            set {
                this.consultoraReqField = value;
                this.RaisePropertyChanged("consultoraReq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCNSXCodigoRequest", WrapperNamespace="http://servicesxsd.cns.ws.corp.yanbal.com", IsWrapped=true)]
    public partial class consultarCNSXCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicesxsd.cns.ws.corp.yanbal.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ActualizacionDatosCampaña.WS.IntegracionWSReq integracionWSReq;
        
        public consultarCNSXCodigoRequest() {
        }
        
        public consultarCNSXCodigoRequest(ActualizacionDatosCampaña.WS.IntegracionWSReq integracionWSReq) {
            this.integracionWSReq = integracionWSReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCNSXCodigoResponse", WrapperNamespace="http://servicesxsd.cns.ws.corp.yanbal.com", IsWrapped=true)]
    public partial class consultarCNSXCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicesxsd.cns.ws.corp.yanbal.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ActualizacionDatosCampaña.WS.IntegracionWSResp integracionWSResp;
        
        public consultarCNSXCodigoResponse() {
        }
        
        public consultarCNSXCodigoResponse(ActualizacionDatosCampaña.WS.IntegracionWSResp integracionWSResp) {
            this.integracionWSResp = integracionWSResp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearContactoRequest", WrapperNamespace="http://servicesxsd.cns.ws.corp.yanbal.com", IsWrapped=true)]
    public partial class crearContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicesxsd.cns.ws.corp.yanbal.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ActualizacionDatosCampaña.WS.IntegracionWSReq1 integracionWSReq;
        
        public crearContactoRequest() {
        }
        
        public crearContactoRequest(ActualizacionDatosCampaña.WS.IntegracionWSReq1 integracionWSReq) {
            this.integracionWSReq = integracionWSReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearContactoResponse", WrapperNamespace="http://servicesxsd.cns.ws.corp.yanbal.com", IsWrapped=true)]
    public partial class crearContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicesxsd.cns.ws.corp.yanbal.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ActualizacionDatosCampaña.WS.IntegracionWSResp1 integracionWSResp;
        
        public crearContactoResponse() {
        }
        
        public crearContactoResponse(ActualizacionDatosCampaña.WS.IntegracionWSResp1 integracionWSResp) {
            this.integracionWSResp = integracionWSResp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSConsultora_SXSDImplChannel : ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSConsultora_SXSDImplClient : System.ServiceModel.ClientBase<ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl>, ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl {
        
        public WSConsultora_SXSDImplClient() {
        }
        
        public WSConsultora_SXSDImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSConsultora_SXSDImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSConsultora_SXSDImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSConsultora_SXSDImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActualizacionDatosCampaña.WS.consultarCNSXCodigoResponse ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl.consultarCNSXCodigo(ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest request) {
            return base.Channel.consultarCNSXCodigo(request);
        }
        
        public ActualizacionDatosCampaña.WS.IntegracionWSResp consultarCNSXCodigo(ActualizacionDatosCampaña.WS.IntegracionWSReq integracionWSReq) {
            ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest inValue = new ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest();
            inValue.integracionWSReq = integracionWSReq;
            ActualizacionDatosCampaña.WS.consultarCNSXCodigoResponse retVal = ((ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl)(this)).consultarCNSXCodigo(inValue);
            return retVal.integracionWSResp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActualizacionDatosCampaña.WS.consultarCNSXCodigoResponse> ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl.consultarCNSXCodigoAsync(ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest request) {
            return base.Channel.consultarCNSXCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActualizacionDatosCampaña.WS.consultarCNSXCodigoResponse> consultarCNSXCodigoAsync(ActualizacionDatosCampaña.WS.IntegracionWSReq integracionWSReq) {
            ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest inValue = new ActualizacionDatosCampaña.WS.consultarCNSXCodigoRequest();
            inValue.integracionWSReq = integracionWSReq;
            return ((ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl)(this)).consultarCNSXCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActualizacionDatosCampaña.WS.crearContactoResponse ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl.crearContacto(ActualizacionDatosCampaña.WS.crearContactoRequest request) {
            return base.Channel.crearContacto(request);
        }
        
        public ActualizacionDatosCampaña.WS.IntegracionWSResp1 crearContacto(ActualizacionDatosCampaña.WS.IntegracionWSReq1 integracionWSReq) {
            ActualizacionDatosCampaña.WS.crearContactoRequest inValue = new ActualizacionDatosCampaña.WS.crearContactoRequest();
            inValue.integracionWSReq = integracionWSReq;
            ActualizacionDatosCampaña.WS.crearContactoResponse retVal = ((ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl)(this)).crearContacto(inValue);
            return retVal.integracionWSResp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActualizacionDatosCampaña.WS.crearContactoResponse> ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl.crearContactoAsync(ActualizacionDatosCampaña.WS.crearContactoRequest request) {
            return base.Channel.crearContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActualizacionDatosCampaña.WS.crearContactoResponse> crearContactoAsync(ActualizacionDatosCampaña.WS.IntegracionWSReq1 integracionWSReq) {
            ActualizacionDatosCampaña.WS.crearContactoRequest inValue = new ActualizacionDatosCampaña.WS.crearContactoRequest();
            inValue.integracionWSReq = integracionWSReq;
            return ((ActualizacionDatosCampaña.WS.WSConsultora_SXSDImpl)(this)).crearContactoAsync(inValue);
        }
    }
}
